/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sickjumps.rollinish.gui;

import com.sickjumps.rollinish.campaign.Campaign;
import com.sickjumps.rollinish.campaign.Encounter;
import com.sickjumps.rollinish.campaign.character.Monster;
import java.awt.Color;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.LineBorder;

/**
 *
 * @author Nathan
 */
public class CampaignViewerFrame extends javax.swing.JFrame {

    private final List<Monster> monsterData;
    private final Campaign campaign;
    
    /**
     * Creates new form CampaignViewerFrame
     */
    public CampaignViewerFrame(Campaign c, List<Monster> monsterData) {
        this.monsterData = monsterData;
        this.campaign = c;
        
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        campaignTextLog = new JTextArea();
        jPanel1 = new JPanel();
        leftButtonPanel = new JPanel();
        btnAddAvailable = new JButton();
        btnRemoveAvailable = new JButton();
        rightButtonPanel = new JPanel();
        btnRemoveActive = new JButton();
        btnNextTurn = new JButton();
        btnAddMonster = new JButton();
        tabEncounters = PaneCreator.createEncounterPane(this.campaign.getEncounters());
        tabMonsterTable = PaneCreator.createMonsterPane(monsterData);
        jMenuBar1 = new JMenuBar();
        mnuFile = new JMenu();
        mnuFileSave = new JMenuItem();
        mnuFileLoad = new JMenuItem();
        jSeparator1 = new JPopupMenu.Separator();
        mnuFileOptions = new JMenuItem();
        jSeparator2 = new JPopupMenu.Separator();
        mnuFileExit = new JMenuItem();
        jMenu2 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        campaignTextLog.setEditable(false);
        campaignTextLog.setColumns(20);
        campaignTextLog.setRows(5);
        jScrollPane1.setViewportView(campaignTextLog);

        jPanel1.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));

        leftButtonPanel.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));

        btnAddAvailable.setText("Add Player");

        btnRemoveAvailable.setText("Remove Player");

        GroupLayout leftButtonPanelLayout = new GroupLayout(leftButtonPanel);
        leftButtonPanel.setLayout(leftButtonPanelLayout);
        leftButtonPanelLayout.setHorizontalGroup(leftButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAvailable, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveAvailable, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftButtonPanelLayout.setVerticalGroup(leftButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAvailable)
                .addGap(65, 65, 65)
                .addComponent(btnRemoveAvailable)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightButtonPanel.setBorder(new LineBorder(new Color(0, 0, 0), 1, true));

        btnRemoveActive.setText("Remove Player");

        btnNextTurn.setText("Next Turn");

        btnAddMonster.setText("Add Custom Enemy");

        GroupLayout rightButtonPanelLayout = new GroupLayout(rightButtonPanel);
        rightButtonPanel.setLayout(rightButtonPanelLayout);
        rightButtonPanelLayout.setHorizontalGroup(rightButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(rightButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveActive, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextTurn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rightButtonPanelLayout.createSequentialGroup()
                        .addComponent(btnAddMonster)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rightButtonPanelLayout.setVerticalGroup(rightButtonPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(rightButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRemoveActive)
                .addGap(18, 18, 18)
                .addComponent(btnNextTurn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(btnAddMonster)
                .addGap(163, 163, 163))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftButtonPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(tabEncounters, GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                    .addComponent(tabMonsterTable))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightButtonPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(leftButtonPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightButtonPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tabEncounters, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabMonsterTable, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        mnuFile.setText("File");

        mnuFileSave.setText("Save...");
        mnuFile.add(mnuFileSave);

        mnuFileLoad.setText("Load...");
        mnuFile.add(mnuFileLoad);
        mnuFile.add(jSeparator1);

        mnuFileOptions.setText("Options...");
        mnuFile.add(mnuFileOptions);
        mnuFile.add(jSeparator2);

        mnuFileExit.setText("Exit");
        mnuFile.add(mnuFileExit);

        jMenuBar1.add(mnuFile);

        jMenu2.setText("Campaign");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAddAvailable;
    private JButton btnAddMonster;
    private JButton btnNextTurn;
    private JButton btnRemoveActive;
    private JButton btnRemoveAvailable;
    private JTextArea campaignTextLog;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JPopupMenu.Separator jSeparator1;
    private JPopupMenu.Separator jSeparator2;
    private JPanel leftButtonPanel;
    private JMenu mnuFile;
    private JMenuItem mnuFileExit;
    private JMenuItem mnuFileLoad;
    private JMenuItem mnuFileOptions;
    private JMenuItem mnuFileSave;
    private JPanel rightButtonPanel;
    private JTabbedPane tabEncounters;
    private JTabbedPane tabMonsterTable;
    // End of variables declaration//GEN-END:variables
}
