/*
 * Copyright (C) 2017 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.sickjumps.rollinish.gui;

import javax.swing.AbstractListModel;
import javax.swing.GroupLayout;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nathan
 */
public class EncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncounterPanel
     */
    public EncounterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vptAvailable = new JScrollPane();
        tblAvailable = new JTable();
        vptActive = new JScrollPane();
        tblActive = new JTable();
        tabMonsterPane = new JTabbedPane();
        vptMonsters = new JScrollPane();
        tblMonsters = new JTable();

        tblAvailable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAvailable.setFillsViewportHeight(true);
        vptAvailable.setViewportView(tblAvailable);

        tblActive.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblActive.setFillsViewportHeight(true);
        vptActive.setViewportView(tblActive);

        tabMonsterPane.setName("monsters"); // NOI18N

        tblMonsters.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMonsters.setFillsViewportHeight(true);
        vptMonsters.setViewportView(tblMonsters);

        tabMonsterPane.addTab("tab1", vptMonsters);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(tabMonsterPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vptAvailable, GroupLayout.PREFERRED_SIZE, 467, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vptActive, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(vptActive)
                    .addComponent(vptAvailable, GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tabMonsterPane, GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTabbedPane tabMonsterPane;
    private JTable tblActive;
    private JTable tblAvailable;
    private JTable tblMonsters;
    private JScrollPane vptActive;
    private JScrollPane vptAvailable;
    private JScrollPane vptMonsters;
    // End of variables declaration//GEN-END:variables
}
