/*
 * Copyright (C) 2017 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.sickjumps.rollinish.gui;

import com.sickjumps.rollinish.ApplicationConfiguration;
import com.sickjumps.rollinish.campaign.Campaign;
import com.sickjumps.rollinish.campaign.CampaignManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author Nathan
 */
public class StartDialog extends javax.swing.JDialog {
    
    private ApplicationConfiguration config;
    private CampaignManager cm;
    private Campaign c;
    
    /**
     * Creates new form StartDialog
     */
    public StartDialog(java.awt.Frame parent, boolean modal, CampaignManager cm, ApplicationConfiguration config) {
        super(parent, modal);
        
        this.cm = cm;
        this.config = config;
        
        initComponents();
        
        configureRecentCampaignButton();
    }
    
    public Campaign getResult() {
        this.setVisible(true);
        return c;
    }
    
    private void configureRecentCampaignButton() {
        String name = config.getLastCampaignName();
        
        if (name.isEmpty()) {
            this.btnMostRecentCampaign.setEnabled(false);
        } else {
            this.btnMostRecentCampaign.setEnabled(true);
            this.btnMostRecentCampaign.setText("Load Recent Campaign: " + name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewCampaign = new JButton();
        btnLoadCampaign = new JButton();
        btnMostRecentCampaign = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        btnNewCampaign.setText("Create New Campaign");
        btnNewCampaign.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnNewCampaignActionPerformed(evt);
            }
        });

        btnLoadCampaign.setText("Load Existing Campaign");
        btnLoadCampaign.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLoadCampaignActionPerformed(evt);
            }
        });

        btnMostRecentCampaign.setText("Most Recent Campaign");
        btnMostRecentCampaign.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMostRecentCampaignActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostRecentCampaign, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewCampaign, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadCampaign, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoadCampaign, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewCampaign, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnMostRecentCampaign, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCampaignActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnNewCampaignActionPerformed
        c = cm.createNewCampaign();
        this.setVisible(false);
    }//GEN-LAST:event_btnNewCampaignActionPerformed

    private void btnLoadCampaignActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLoadCampaignActionPerformed
        c = cm.loadExistingCampaign();
        this.setVisible(false);
    }//GEN-LAST:event_btnLoadCampaignActionPerformed

    private void btnMostRecentCampaignActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMostRecentCampaignActionPerformed
        c = cm.loadMostRecentCampaign();
        this.setVisible(false);
    }//GEN-LAST:event_btnMostRecentCampaignActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLoadCampaign;
    private JButton btnMostRecentCampaign;
    private JButton btnNewCampaign;
    // End of variables declaration//GEN-END:variables
}
